/// Header file generated by CMake
/**
* @file   Version.hpp
*/
#pragma once

/// The library's version number as a dotted triplet string.
/**
 * @code
 * 2.1.1
 * @endcode
 */
#define AISAKA_VERSION "2.1.1"

/// The library's major version number.
#define AISAKA_VERSION_MAJOR "2"

/// The library's minor version number.
#define AISAKA_VERSION_MINOR "1"

/// The library's patch number.
#define AISAKA_VERSION_PATCH "1"
